### ISSUE TITLE
Error handling for local installs is unhelpfully vague

### ISSUE THREAD

**Issue by anowlcalledjosh** [mitsuhiko/pipsi#101]
### Problem

Any error in the setup.py of the package to be installed (i.e. nonzero return code from `python setup.py --name`) will result in `<package> does not appear to be a local Python package`. This is less than helpful if, for example, the problem is that there's a syntax error in setup.py.

### Expected

pipsi should give useful error messages if it can't install a local package.

### Actual

If anything unexpected happens during installation, pipsi declares that the problem is that your package "does not appear to be a local Python package".

Relevant code: [pipsi.py:197](https://github.com/mitsuhiko/pipsi/blob/11cdec37884eb1bd3b0bb48057c0dc0503d7b940/pipsi.py#L197)

I would suggest a new error message like `<package> could not be installed. Error from setup.py: ...`); I can probably open a PR for that at some point if it looks good.

**Comment by RonnyPfannschmidt** [comment]
to solve this more nice, there should be a check for a setup.py existing as well, so we can differentiate between not a package and not a working setup.py

**Comment by 00willo** [comment]
Just thought I'd add a small gotcha here, as I just hit it. 

Make sure the package that you're trying to install from pip doesn't happen to also be the name of a folder in your PWD. 

I knew the command was correct as I was reusing the one from my history where I needed a version of python I'd grabbed via pyenv.
