### ISSUE TITLE
Allow to installation of more packages into a venv

### ISSUE THREAD

**Issue by kwbr** [mitsuhiko/pipsi#13]
Say I have installed beet (http://beets.radbox.org/) with pipsi. beet has some optional dependencies which need to be installed if you enable one of the provided plugins. To use discogs you need the discogs-client package, to use lastgenre you need the pylast package.

So, in order to use those plugins it should be possible to install more packages into the venv.

**Comment by RonnyPfannschmidt** [comment]
This one is depending on #52

**Comment by RonnyPfannschmidt** [comment]
Aside from package we also should handle scripts as per #29

**Comment by glyph** [comment]
Another great example here:

`pipsi install devpi-web` and `pipsi install devpi` both fail.

But, `pipsi install devpi-server` doesn't install devpi-web, which means I don't get the nice web UI.

**Comment by dhouck** [comment]
This also makes it really difficult to use Jupyter, *especially* if you want multiple kernels or to work with other packages in Jupyter.

**Comment by vlcinsky** [comment]
What about using sort of `requirements.txt`, but named according to virtualenv I want to use.

E.g. I want to install `devpi` with `devpi-client` and `devpi-web`.

I would create a `devpi.requirements` (just properly named `requirements.txt`):
```
devpi-client
devpi-server
devpi-web
```
and run:
```bash
$ pipsi install -r devpi.requirements
```
It would create virtualenv named `devpi.requirements`, install into it all the dependencies and symlink all the CLIs available. The file `devpi.requirements` would be placed into root of the virtualenv under name `requirements.txt` to have base for later upgrades.

It would be recommended to use the requirements without frozen version to allow updates.

With CLI symlinks and multiple packages installed into one virtualenv it is a bit more likely, more than one virtualenv will have CLI with conflicting name. This can happen today, but it would be a bit more likely.

**Comment by kwbr** [comment]
stale
