### ISSUE TITLE
Pipsi always uses Python 2 to install

### ISSUE THREAD

**Issue by gwerbin** [mitsuhiko/pipsi#132]
```
$ /usr/local/bin/python3 get-pipsi.py --src='git+https://github.com/mitsuhiko/pipsi.git#egg=pipsi'
Installing pipsi
Running virtualenv with interpreter /usr/bin/python2
```
How do I fix or debug this? I'm using Debian 9.

**Comment by anlutro** [comment]
If you uninstall `virtualenv` and `python3-virtualenv` but install `python3-venv`, the script does what it's supposed to. However, you still need to reinstall `virtualenv` afterwards. Very annoying.
