### ISSUE TITLE
Accept "scripts" keyword as a script to install.

### ISSUE THREAD

**Issue by Qu4tro** [mitsuhiko/pipsi#14]
Some packages use the scripts keyword in setup.py instead of entry_point as a way to install scripts.

Some investigation into the code, reveals, that find_links(the function responsible to find those scripts), only checks out the entry_point entry. 

I'm not much of a expert on the python ecosystem, but I'll be glad to help, if you need anything.

PS: That Popen hack is scary, and I have no idea why it's there.

**Comment by blueyed** [comment]
A test case is https://github.com/hut/ranger.git.

A solution to this might be running `setup.py` from `find_scripts`:

    % ./setup.py --dry-run install_scripts --skip-build 
    running install_scripts
    changing mode of /home/daniel/.pyenv/versions/3.4.2/bin/ranger
    changing mode of /home/daniel/.pyenv/versions/3.4.2/bin/rifle

`setup.py` can be found / verified to exist via `dist.has_metadata('../setup.py')`.

> PS: That Popen hack is scary, and I have no idea why it's there.

Do you mean the use of `Popen` in the first place, or how it's being called?

**Comment by Qu4tro** [comment]
How it's called. On the find_scripts function.

**Comment by RonnyPfannschmidt** [comment]
fins-scripts is a best-effort function using install metadata, please use entrypoints and/or setuptools

**Comment by RonnyPfannschmidt** [comment]
as extra info, POpen is necessary, since we need to find the scripts in a target virtualenv while installation is in a non-target virtualenv,

in future we could maybe use a pkg_resources working-set of the sitedir of the referred virtualenv,
