### ISSUE TITLE
pipsi adding ~/.local/bin to bashrc should be configured by a parameter

### ISSUE THREAD

**Issue by msdos** [mitsuhiko/pipsi#158]
Something like `--dont-add-to-bashrc` or a parameter in get-pipsi.py itself. Some people have their dotfiles versioned.

**Comment by cs01** [comment]
`--no-modify-path` is already an option

**Comment by msdos** [comment]
You're right, I just read the source code.

**Comment by msdos** [comment]
This should be added to the documentation.

**Comment by msdos** [comment]
This was added 6 days ago https://github.com/mitsuhiko/pipsi/commit/a2ece994a99e162998c24958dee9871fabc9f7b7 @RonnyPfannschmidt would you mind adding this to the docs?

**Comment by cs01** [comment]
I added it, he merged it. I can update the docs.
