### ISSUE TITLE
Use pipsi's python to install packages

### ISSUE THREAD

**Issue by blueyed** [mitsuhiko/pipsi#23]
`pipsi install` should maybe use the same python version it is being run under for `install`.

    % head -n1 =pipsi
    #!/home/user/.local/venvs/pipsi/bin/python
    % /home/user/.local/venvs/pipsi/bin/python --version
    Python 2.7.8
    % pipsi install .
    Using base prefix 'pyenv/3.4.1'
    New python executable in /home/user/.local/venvs/ranger/bin/python3.4
    …

I've installed pipsi explicitly using Python 2 and expected that packages installed through it would be installed using the same python version.

**Comment by RonnyPfannschmidt** [comment]
needs a configuration file in some way, takes a while

**Comment by blueyed** [comment]
An idea would be to look at and use the shebang line from the `pipsi` script?!

**Comment by RonnyPfannschmidt** [comment]
im thinking of using sys.executable by default
