### ISSUE TITLE
Result: "Did not find any scripts.  Uninstalling."

### ISSUE THREAD

**Issue by zoresvit** [mitsuhiko/pipsi#25]
For some of the packages (like [sh](http://amoffat.github.io/sh/)) I get reponse *"Did not find any scripts.  Uninstalling."* at the end of installation process and the package isn't installed:

```
$ pipsi install sh
New python executable in /home/zoresvit/.local/venvs/sh/bin/python
Installing setuptools, pip...done.
Downloading/unpacking sh
  Using download cache from /home/zoresvit/.pip/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fs%2Fsh%2Fsh-1.09.tar.gz
  Running setup.py (path:/home/zoresvit/.local/venvs/sh/build/sh/setup.py) egg_info for package sh
    
Installing collected packages: sh
  Running setup.py install for sh
    
Successfully installed sh
Cleaning up...
Did not find any scripts.  Uninstalling.
```

Is there a way to workaround this and keep all the packages using `pipsi`?

**Comment by untitaker** [comment]
Why do you want this? Does sh have any scripts?

**Comment by zoresvit** [comment]
@untitaker would be helpful if the behavior was less confusing so one doesn't have to look into source code of every single package to find out.

**Comment by untitaker** [comment]
To find out what?

**Comment by zoresvit** [comment]
@untitaker Are you trolling? The answer to your question —- "Does sh have any scripts?". At first usage this `pipsi` message looks odd since it's coming right after "Successfully installed sh" message.

**Comment by untitaker** [comment]
Pipsi just told you that it couldn't find any scripts. Not finding *any* scripts already answers that question.

**Comment by untitaker** [comment]
And no, I am not trolling (thanks). Maybe pipsi's error message needs to be clarified though.

**Comment by zoresvit** [comment]
@untitaker No, it's fine — it seems I just didn't quite get `pipsi`'s purpose from the first time, now it make sense :)

Even though I still think that message "Did not find any scripts.  Uninstalling." coming right after "Successfully installed <module>" looks odd :)

**Comment by untitaker** [comment]
I agree, pipsi's output is not very informative.

**Comment by fabiocerqueira** [comment]
Try: `pipsi upgrade pipsi`
