### ISSUE TITLE
multi package envs

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [mitsuhiko/pipsi#29]
i'd like to use a single pipsi env for tox and detox, and get the tox and detox scripts
currently there is no way to setup something like that

i suggest a optional parameter for extra packages

**Comment by brosner** [comment]
I agree it would be good to allow extra packages at install time. As a workaround I do this to get multi-packages in a single environment:

    pipsi install stellar
    ~/.local/venvs/stellar/bin/pip install psycopg2

**Comment by ryneeverett** [comment]
Is this the same as #13?

**Comment by RonnyPfannschmidt** [comment]
Not quite, but that's easily consolidated
Thanks for the hint
