### ISSUE TITLE
Install multiple versions of the same package

### ISSUE THREAD

**Issue by t00f** [mitsuhiko/pipsi#33]
Hi guys,

I am looking to `pipsi` while looking for a *proper* way to install multiple version of a package and its dependencies.

I am well aware that `virtualenv` main purpose is to separate contexts but I would need to find a way to install multiple version of the same package within the same environment. 

`pipsi` seems to have a great approach but the package name is used to determine the virtualenv name in `~/.local/venvs/` and the symlink in `~/.local/bin`. 

It might be an idea to compute a `virtualenv` name based on the package name and the version. Using PR #28 accepting settings from environment variable, it should be also possible to configure multiple `pipsi` environments.

I don't know if it would be possible or not but I'd like to ask for your thoughts ?

Here would be a simple case scenario where `myLib 1.0` relies on `requests v1.2` and `myLib 2.0` relies on `requests v2.0` for instance:

```python
from myLib_1_0 import MyObject as MyObject1
from myLib_2_0 import MyObject as MyObject2

# Do some work to migrate a MyObject1 instance to a MyObject2 instance.
```

Thanks!

**Comment by RonnyPfannschmidt** [comment]
different envs/installs are completely independent

no multi version import is a shortcoming of python itself - but proper solutions are hard
