### ISSUE TITLE
override default location for pipsi using an environment variable

### ISSUE THREAD

**Issue by pigeonflight** [mitsuhiko/pipsi#35]
Currently pipsi wants to put things in ~/.local

I'd like to be able to set an environment variable (e.g. $PIPSI_LOCAL_DIR) which pipsi uses to determine the location of the `.local` folder. 

My usecase:
I'm on a Chromebook, using crouton and ~/.local happens to be located on a partition that has no space. The ~/Downloads folder actually has space. If I were able to `export PIPSI_LOCAL_DIR=$HOME/Downloads/.local` then I would be able to have my packages on a partition with space. (Normally I'd use symlinking but I get errors related to multiple levels of symlinks)
Implementing this simple feature would open the use of pipsi to Chromebook/crouton users.

**Comment by benwebber** [comment]
You may be interested in #28, which adds similar environment variables.

**Comment by RonnyPfannschmidt** [comment]
fixed by #28
