### ISSUE TITLE
Did not find any scripts.  Uninstalling. (only with --editable)

### ISSUE THREAD

**Issue by amiorin** [mitsuhiko/pipsi#40]
```
pipsi install /path/to/project
```
works

```
pipsi install --editable /path/to/project
```
doesn't work

my ``setup.py`` contains
```
    scripts=['bin/run-consul'],
```

**Comment by RonnyPfannschmidt** [comment]
does it change if you use the console-scripts entry-point instead
develop installed plain script are not discoverable, develp is a setuptools feature, scripts is just there for backward compat, setuptools itself uses console_scripts, which get generated and recorded propperly

**Comment by amiorin** [comment]
it works with console-scripts. I've switched to console-scripts
