### ISSUE TITLE
"pip install" should exit non-zero if it failed with "Did not find any scripts.  Uninstalling."

### ISSUE THREAD

**Issue by blueyed** [mitsuhiko/pipsi#46]
Currently it does exit with 0.

    % pipsi install ranger
    Already using interpreter …/pyenv/3.4.3/bin/python3.4
    Using base prefix '…/pyenv/3.4.3'
    New python executable in /home/user/.local/venvs/ranger/bin/python3.4
    Also creating executable in /home/user/.local/venvs/ranger/bin/python
    Installing setuptools, pip...done.
    You are using pip version 6.1.1, however version 7.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Collecting ranger
      Using cached ranger-0.9.tar.gz
    Installing collected packages: ranger
      Running setup.py install for ranger
    Successfully installed ranger-0.9
    Did not find any scripts.  Uninstalling.
    % echo $?
    0

Maybe with `os.EX_CANTCREAT` (73 for me), but that might not be defined(?!):

>    Exit code that means a user specified output file could not be created.
    Availability: Unix.

**Comment by untitaker** [comment]
Decided to use exitcode `1` for everything for now.

**Comment by blueyed** [comment]
Seems to be good, thanks!
