### ISSUE TITLE
Manual package install option

### ISSUE THREAD

**Issue by erikcw** [mitsuhiko/pipsi#57]
It would be helpful to have an option for pipsi install that would prevent it from uninstalling if it can't find any scripts. Maybe print out a big warning message if that happens with instructions on how to manually create the symlinks. Kind of like how homebrew guides similar issues with brew install.

I imaging there are a lot of projects that are "a total mess"... :-)

Originally mentioned in #56

**Comment by untitaker** [comment]
Perhaps pipsi should not rely on setuptools entry points and instead diff the bin folder.

On 12 August 2015 19:07:53 CEST, Erik Wickstrom <notifications@github.com> wrote:
>It would be helpful to have an option for pipsi install that would
>prevent it from uninstalling if it can't find any scripts. Maybe print
>out a big warning message if that happens with instructions on how to
>manually create the symlinks. Kind of like how homebrew guides similar
>issues with brew install.
>
>I imaging there are a lot of projects that are "a total mess"... :-)
>
>Originally mentioned in #56 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/pipsi/issues/57

-- 
Sent from my phone. Please excuse my brevity.

**Comment by RonnyPfannschmidt** [comment]
Superseded
