### ISSUE TITLE
Support creating a virtualenv with --system-site-packages

### ISSUE THREAD

**Issue by garyp** [mitsuhiko/pipsi#59]
I have some python software that has a dependency on a system-provided python library that isn't available via the usual means (pip, etc.). I still want to install the software into a virtualenv, using pipsi, but I need pipsi to create the virtualenv using `virtualenv --system-site-packages`. Can this be added as an option to `pipsi install`?

**Comment by RonnyPfannschmidt** [comment]
Yes but since its run on volunteer time it's fastest to implement in a pr

**Comment by garyp** [comment]
Ok, well good to hear that you don't have any objections. I'm stretched pretty thin right now, but I'll try to look through pipsi source and make a PR when I have some time.
