### ISSUE TITLE
Would you like to register this package with homebrew?

### ISSUE THREAD

**Issue by c-bata** [mitsuhiko/pipsi#60]
This tool is awesome!
But I would like to manage this package with homebrew on Mac OSX.

Do you have any plans to register this with homebrew?

**Comment by RonnyPfannschmidt** [comment]
as things are now none of the contribution mac users have the time

**Comment by RonnyPfannschmidt** [comment]
@c-bata would you be interested in maintaining one?

**Comment by c-bata** [comment]
Okay! I'll give it a try.

**Comment by RonnyPfannschmidt** [comment]
@c-bata could you perhaps refer a homebrew issue/PR retarding this topic, or close the issue?

**Comment by zbeekman** [comment]
It would be easy if pipsi were in PyPi, because then you could use pypi_homebrew_poet

**Comment by zbeekman** [comment]
Oops, it is in PyPi.... Is it up to date? Yes, 0.9 in homebrew and on GH. Many commits to master since then? Nope [just a few](https://github.com/mitsuhiko/pipsi/compare/0.9...master)....

I'll see if I can whip up a quick Homebrew PR.... I need to create two other small ones soon anyway

Here is the poet output:
```ruby
class Pipsi < Formula
  homepage "http://github.com/mitsuhiko/pipsi/"
  url "https://pypi.python.org/packages/source/p/pipsi/pipsi-0.9.tar.gz"
  sha256 "688b688cc8a7a76612c0d4d1839aaef98ece8382d4382b9d8b6f0caa65f0ed34"

  depends_on :python if MacOS.version <= :snow_leopard

  resource "click" do
    url "https://pypi.python.org/packages/source/c/click/click-6.2.tar.gz"
    sha256 "fba0ff70f5ebb4cebbf64c40a8fbc222fb7cf825237241e548354dabe3da6a82"
  end

  resource "virtualenv" do
    url "https://pypi.python.org/packages/source/v/virtualenv/virtualenv-13.0.3.tar.gz"
    sha256 "355e46928c2b00b83b7d00d70d5adc529e9c2fe1f366b07e8a1b49cd8c5bd1b9"
  end

  def install
    ENV.prepend_create_path "PYTHONPATH", libexec/"vendor/lib/python2.7/site-packages"
    %w[click virtualenv].each do |r|
      resource(r).stage do
        system "python", *Language::Python.setup_install_args(libexec/"vendor")
      end
    end

    ENV.prepend_create_path "PYTHONPATH", libexec/"lib/python2.7/site-packages"
    system "python", *Language::Python.setup_install_args(libexec)

    bin.install Dir[libexec/"bin/*"]
    bin.env_script_all_files(libexec/"bin", :PYTHONPATH => ENV["PYTHONPATH"])
  end
end
```

**Comment by zbeekman** [comment]
The biggest issue will be the `test do` block and finding a suitable test for this...

**Comment by zbeekman** [comment]
https://github.com/Homebrew/homebrew/pull/49043

**Comment by zbeekman** [comment]
Ah yes, I forgot that, generally, the Homebrew folks don't like self upgrading packages... See https://github.com/Homebrew/homebrew/pull/49043#issuecomment-183570081  I'm not sure how this will play out, whether or not they will accept the formula.

**Comment by zbeekman** [comment]
Hi guys, got some more feedback from the Homebrew maintainers and tried my hand at implementing a `test do` block. This runs fine on my local machine, but fails mysteriously when run with Homebrew's CI and deployment Jenkins tests. Would someone mind taking a look at the errors? http://bot.brew.sh/job/Homebrew%20Pull%20Requests/42112/

**Comment by c-bata** [comment]
Sorry, I didn't do anything. closing this.
