### ISSUE TITLE
A means of disabling the self update feature for Homebrew installs

### ISSUE THREAD

**Issue by zbeekman** [mitsuhiko/pipsi#68]
@domT4 (Homebrew team) said:
> Is there any way to disable the self-update feature? That sort of thing doesn't really play nice with package management

And then:
> It's not necessarily a blocker but ideally we'd file an Issue upstream asking for a way to disable the self-update mechanism impacting the tool itself specifically.

So they may not accept the Homebrew formula unless there is a build time option that will disable `pispsi upgrade pipsi`. Would this be possible to do?

Thanks

**Comment by RonnyPfannschmidt** [comment]
as far as i understood pipsi installed by homebrew is not in a pipsi managed python,

i would gladly accept a pull request that makes pipsi update pipsi fail with a error whenever that is the case

**Comment by zbeekman** [comment]
> as far as i understood pipsi installed by homebrew is not in a pipsi managed python,

What do you mean by pipsi managed python?

> i would gladly accept a pull request that makes pipsi update pipsi fail with a error whenever that is the case

Cool. Unfortunately, at the moment, I don't have the time or the knowhow to implement this. I suspect if the pipsi project formalizes that this is a goal they would like to work towards, that could be enough to get the Homebrew folks to accept the package formula as it stands, for the time being, but IDK for sure.

**Comment by RonnyPfannschmidt** [comment]
As in, if you install pipsi in homebrew its not installed in the pipsi env folder, but the homebrew folder

So when pipsi update pipsi is tried, it can take a look and decide based on its own location

**Comment by zbeekman** [comment]
Closing this because pipsi (in it's current state) is rejected from homebrew.
