### ISSUE TITLE
Unable to install `jupyter` meta package with pipsi

### ISSUE THREAD

**Issue by scolby33** [mitsuhiko/pipsi#74]
The `jupyter` package is used to install all of Jupyter's cli tools and dependencies at once. Unfortunately, it doesn't provide any console scripts in its `setup.py`, instead relying on the console scripts declarations in its dependencies. `pipsi` doesn't seem able to detect these.

Any ideas how to successfully install this package with `pipsi`?

Compare jupyter/jupyter/pull/149 (unfortunately, this doesn't end up working completely either)

**Comment by untitaker** [comment]
I don't see anything that we can do, except provide more options to make installation of Jupyter possible (which defeats pipsi's purpose of not having to fiddle with virtualenvs, binaries and setuptools).

**Comment by scolby33** [comment]
That's unfortunate to hear, but thanks for the quick response! I'll live with manually symlinking out of a virtualenv for now.

**Comment by RonnyPfannschmidt** [comment]
a command that symlinks a given package might be ok

bookkeeping would be nice to have

**Comment by iamale** [comment]
It's not _that_ hard, I believe. One option could be to install the package normally, then look at `~/.local/venvs/[package-name]/bin` and prompt user which binaries do they want to symlink.

**Comment by aboutaaron** [comment]
Is there any follow up on this? I really enjoy pipsi and would like to somehow get jupyter working with it. Any guidance would be helpful!

**Comment by imcery** [comment]
I managed to install jupyter by manually creating jupyter's venv so pipsi can track it correctly.

    $ python -m virtualenv /Users/user/.local/venvs/jupyter
    $ source /Users/user/.local/venvs/jupyter/bin/activate
    $ pip install jupyter

Now we have to just create symlinks and we are done.

    $ cd /Users/user/.local/bin
    $ ln -s ../venvs/jupyter/bin/jupy* .

Verify by running `pipsi list`

    Package "jupyter":
      jupyter-run
      jupyter-nbextension
      jupyter-notebook
      jupyter-nbconvert
      jupyter-troubleshoot
      jupyter-migrate
      jupyter-console
      jupyter-serverextension
      jupyter-trust
      jupyter-qtconsole
      jupyter-kernelspec
      jupyter-kernel
      jupyter
      jupyter-bundlerextension

**Comment by scolby33** [comment]
I've found that there's no need to link all the binaries, only `jupyter`. The canonical way to call `jupyter-qtconsole`, for example is to run `jupyter qtconsole` and let the plain `jupyter` binary dispatch to `jupyter-qtconsole`. Just linking `jupyter` into the bin directory still allows all the sub-binaries to be found.

Not that it changes the difficulty of the process, but it helps to keep the bin directory clean if that's something you care about.

**Comment by gagoman** [comment]
You can also use `pipsi` to install `jupyter-core` and then manually use that env to install extra dependencies.

**Comment by iamale** [comment]
So basically it is, once again (for the sake of copypastability):

```bash
virtualenv -p python3 ~/.local/venvs/jupyter
~/.local/venvs/jupyter/bin/pip install jupyter
ln -s ../venvs/jupyter/bin/jupyter ~/.local/bin/jupyter
```

And then it would be upgradable via pipsi like the rest of packages.

**Comment by naiveai** [comment]
Simply installing `jupyter_core` with pipsi worked fine for me. For reference, running Arch Linux, so if you are too, you might want to try just doing that.

**Comment by laike9m** [comment]
To elaborate @gagoman's comment, I'll post what's been working for me:

```
pipsi install jupyter-core/bin
~/.local/venvs/jupyter-core/bin/pip install jupyter
```

Done.

**Comment by jkinred** [comment]
With `jupyter-core` I didn't have the notebook, this works:
```
pipsi install jupyter-core
pipsi install notebook
```
