### ISSUE TITLE
pipsi uses virtualenv found in $PATH instead of its own

### ISSUE THREAD

**Issue by sanjioh** [mitsuhiko/pipsi#75]
Hi,

is there any reason pipsi uses virtualenv binary found in $PATH instead of the one in its own virtualenv? This prevents from having the system Python installation clean of every third party tools.

E.g.
pip3.5 install virtualenv
curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3.5
pip3.5 uninstall virtualenv
pipsi install pylint
FileNotFoundError: [Errno 2] No such file or directory: 'virtualenv'

Of course if I instead repeat the procedure with pipsi's virtualenv activated it works perfectly.

The fix should be a matter of changing line 233:

`args = ['virtualenv', '-p', python or sys.executable, venv_path]`

into something like:

`args = [os.path.join(os.path.dirname(sys.executable), 'virtualenv'), '-p', python or sys.executable, venv_path]`

I apologize if I am missing something obvious.

Thanks

**Comment by RonnyPfannschmidt** [comment]
windows support as one

erhaps we should switch to a model where python -m virtualenv is used 

up for making that pr?

**Comment by sanjioh** [comment]
Yes,  I'd like to. I don't have any experience in Windows Python development, though. I'll do my best :) 

Any contribution guideline you want to provide?

**Comment by glyph** [comment]
I just bumped into this as well.

I'm trying to adjust my environment to avoid `pip install`ing anything into my "global" python environment, except for `pip`, and not adding the user-scripts directory (in my case, `~/Library/Python/2.7/bin/`, _not_ the shared `~/.local/bin` that pipsi uses).  If a tool is something I just want to ''use'' (i.e. I'm not writing my own Python code for it) then it should have its own isolated dependencies so it doesn't break if I `pip install --upgrade` something; if a tool is a development tool that requires execution of Python code, then it should only be installed in my development virtualenvs to avoid confusion.  So I decided pipsi should be in charge, and only pipsi binaries should ever be on my path!  But then I had to hack around bootstrapping `virtualenv`

**Comment by feigaochn** [comment]
I have a related question.

How to install packages with different Python versions as backend, something like `pipsi` vs `pipsi3`.

**Comment by wsanchez** [comment]
I suspect this is the cause of my breakage:

```console
[tool:~] (master) wsanchez$ pipsi install tox
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/wsanchez/.local/venvs/tox/bin/python3
Also creating executable in /Users/wsanchez/.local/venvs/tox/bin/python
Installing setuptools, pip, wheel...done.
Collecting tox
  Using cached tox-2.5.0-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.3.0 (from tox)
  Using cached pluggy-0.4.0-py2.py3-none-any.whl
Collecting py>=1.4.17 (from tox)
  Using cached py-1.4.31-py2.py3-none-any.whl
Collecting virtualenv>=1.11.2 (from tox)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Installing collected packages: pluggy, py, virtualenv, tox
Successfully installed pluggy-0.4.0 py-1.4.31 tox-2.5.0 virtualenv-15.1.0
  Linked script /Users/wsanchez/.local/bin/tox
  Linked script /Users/wsanchez/.local/bin/tox-quickstart
Done.
[tool:~] (master) wsanchez$ tox flake8
Traceback (most recent call last):
  File "/Users/wsanchez/.local/bin/tox", line 7, in <module>
    from tox import cmdline
ModuleNotFoundError: No module named 'tox'
```

Of course tox is installed at `~/.local/venvs/tox` but the `tox` executable isn't looking there.  Isn't that the whole point of `pipsi`?  I notice that the `tox` executable has this shebang line:

```
#!/usr/local/bin/python3
```

Seems like that should use the python in the tox venv, not the python used to run `pipsi`.

**Comment by wsanchez** [comment]
FWIW, changing the shebang line does fix it for me.

**Comment by piotr-dobrogost** [comment]
[Off-topic]

@glyph 
> (...) and not adding the user-scripts directory (in my case, ~/Library/Python/2.7/bin/, not the shared ~/.local/bin that pipsi uses)

May I ask why?
