### ISSUE TITLE
Pipsi installer - confused about $PATH and module

### ISSUE THREAD

**Issue by pikeas** [mitsuhiko/pipsi#87]
$ curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3
    <...>
    Installed pipsi binary in /Users/me/.local/bin

    ============================================================

    Warning:
      It looks like /Users/me/.local/bin is not on your PATH so pipsi will
      not work out of the box.  To fix this problem make sure to
      add this to your .bashrc / .profile file:

      export PATH=/Users/me/.local/bin:$PATH

    ============================================================

    pipsi is now installed.

    $ echo $PATH
    /Users/me/.local/bin:<other items on PATH>
    $ which pipsi
    /Users/me/.local/bin/pipsi

    $ pipsi
    Traceback (most recent call last):
      File "/Users/me/.local/bin/pipsi", line 7, in <module>
        from pipsi import cli
    ModuleNotFoundError: No module named 'pipsi'

I'm running zsh 5.3.1.

**Comment by ryneeverett** [comment]
This is a python path issue, not a shell path issue. Are you sure there weren't any errors in the ellipsized part?

**Comment by RonnyPfannschmidt** [comment]
Looks like a initial / is missing in the path, i suspect this wouldn't work on Unix/bsd

**Comment by pikeas** [comment]
I re-installed Python 3 (homebrew) and pipsi installed without issue. Closing due to gremlins.

**Comment by RonnyPfannschmidt** [comment]
thanks for the update 👍

**Comment by jononomo** [comment]
I had precisely the same issue
