### ISSUE TITLE
User install in pip.conf let's pipsi fail

### ISSUE THREAD

**Issue by funkyfuture** [mitsuhiko/pipsi#90]
if a user has a `pip.conf` with the following content

    [global]
    user = true 

any `pipsi install` fails with this message

    Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
    Failed to pip install.  Aborting.
    
afaict `pip` has no command-line option to override that setting. :-/

**Comment by RonnyPfannschmidt** [comment]
as pip is the origin we cant fix it - please raise an issue with pip

**Comment by BurhanDanger** [comment]
What I'm currently doing is I have `export PIP_USER=yes` in .bash_profile and to override that environment variable pipsi is alias of `PIP_USER= pipsi`
