### ISSUE TITLE
pipsi does not support the subdirectory component

### ISSUE THREAD

**Issue by caipre** [mitsuhiko/pipsi#94]
```
pkg_resources.RequirementParseError: Invalid requirement, parse error at "u'&subdire'"
```

No idea why `subdirectory` is cut off in the above exception.

From `pip` docs:

> For projects where setup.py is not in the root of project, "subdirectory" component is used. Value of "subdirectory" component should be a path starting from root of the project to where setup.py is located.

https://pip.pypa.io/en/stable/reference/pip_install/?highlight=subdirectory#vcs-support

**Comment by RonnyPfannschmidt** [comment]
the given error is unrelated to pip to begin with - please retry a complete error report

**Comment by RochesterinNYC** [comment]
I'm coming across this issue as well.

I was trying to install via:
`pipsi install git+https://ghe.<enterprise>.net/<org>/<repo>#egg=<package>#subdirectory=<subdir>`
