### ISSUE TITLE
`pipsi upgrade package` fails if package was installed from git

### ISSUE THREAD

**Issue by pjz** [mitsuhiko/pipsi#96]
It's nice that I can do:

`pipsi install git+ssh://git@github.com/me/mypackage.git#egg=mypackage`

but if i subsequently do

`pipsi upgrade mypackage`

then the dependencies run through being upgraded, but the package itself isn't re-pulled. :(

**Comment by vinzenz** [comment]
somehow I would expect you having to run `pipsi upgrade git+ssh://git@github.com/me/mypackage.git#egg=mypackage`

**Comment by pjz** [comment]
Ugh, it looks like pip itself is inconsistent here: you do have to do `pip install --upgrade git+ssh://git@github.com/me/mypackage.git#egg=mypackage` but you apparently do `pip uninstall mypackage` (per [Stackoverflow](https://stackoverflow.com/questions/8926566/how-to-uninstall-a-git-repo-using-pip)).  I was expecting to be able to use the egg/venv name to be able to do upgrades, I guess.  That said, does `pipsi upgrade git+ssh://git@github.com/me/mypackage.git#egg=mypackage
` work?

**Comment by pjz** [comment]
project unmaintained; use pipx

**Comment by ltc1996** [comment]
已经收到了您的邮件，我会尽快回复的。
