### ISSUE TITLE
Cannot install pipsi mac

### ISSUE THREAD

**Issue by yochem** [mitsuhiko/pipsi#97]
macOS version: 10.12.14

I tried to install pipsi using `curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python` but my prompt shows this: 
```bash
...
============================================================

Warning:
  It looks like /Users/Yochem/.local/bin is not on your PATH so pipsi will
  not work out of the box.  To fix this problem make sure to
  add this to your .bashrc / .profile file:

  export PATH=/Users/Yochem/.local/bin:$PATH

============================================================

pipsi is now installed.
```
I tried to fix it using `echo 'export PATH=/Users/Yochem/.local/bin:$PATH' >>~/.bashrc` and `...>>~/.profile`.

But when I try to install [cookiecutter](https://github.com/audreyr/cookiecutter), I get: `bash: pipsi: command not found`

**Comment by RonnyPfannschmidt** [comment]
please take a look into those folders, it seems like something is missing if the command still doesnt work

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of feeback
